"""Stage U0 gate evidence: reports/source_verification_USA.md
(REPLICATION_KICKOFF.md §12 Stage U0, Gate U0; D-S16-011).

Measured from the harvested snapshots and the built canonical layer — never
hand-filled (D13): first and last year per (line, source) for all 41 USA
lines (from `ggfiscal coverage`), the D26 Level II proxy shares, the
sales-grossing and enterprise wedges of kickoff §3, the §8.2 base-year
bridge on the latest WEO vintage with the perimeter rule, the three
structural zeros in the anchor, the blocked hosts and the harvest record.

    python3 tools/source_verification_usa.py     # after fetch, coverage, build, reconcile
"""
from __future__ import annotations

import datetime as dt
import json
import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from ggfiscal import config  # noqa: E402
from ggfiscal.ingest.endpoints import weo_vintages  # noqa: E402
from ggfiscal.standardise import readers as R  # noqa: E402
from ggfiscal.standardise import readers_bea as RB  # noqa: E402
from ggfiscal.standardise import readers_oecd as RO  # noqa: E402

ISO3 = "USA"


def _mn(x: float) -> str:
    return f"{x:,.0f}"


def _harvest_record() -> list[dict]:
    """The latest usable snapshot per USA-relevant (source, part)."""
    keep = ("OECD_T12_EXP", "OECD_T12_REV", "OECD_T12_BAL", "OECD_T10", "OECD_T1", "OECD_EO",
            "OECD_T11", "OECD_RS", "IMF_GFS", "BEA_NIPA", "FRB_Z1", "OMB_BUDGET", "CBO_BASELINE",
            "CMS_TRUSTEES", "EC_AMECO")
    rows = []
    for (sid, part), e in sorted(R.latest_snapshots().items()):
        if sid in keep and (part in ("", "annual", "quarterly", "register", "current",
                                     "expanded_tables_2026", "baselines", "actuals")
                            or "USA" in part or sid in ("OMB_BUDGET", "EC_AMECO")):
            rows.append({"source_id": sid, "part": part, "retrieved": e["retrieved_at"],
                         "sha256": e["sha256"][:12], "bytes": e.get("size", "")})
        if sid.startswith("IMF_WEO_") and part.startswith("USA_"):
            rows.append({"source_id": sid, "part": part, "retrieved": e["retrieved_at"],
                         "sha256": e["sha256"][:12], "bytes": e.get("size", "")})
    return rows


def main() -> Path:
    fam = config.family(ISO3)
    t12 = lambda item, flow: RO.oecd_t12(ISO3, item, flow)  # noqa: E731
    cov = pd.read_csv(REPO / "reports" / "coverage_matrix_v0.csv")
    cov = cov[cov.iso3 == ISO3]
    out: list[str] = []
    now = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    out += [f"# Source verification — United States (Stage U0, kickoff §12; generated {now})",
            "",
            "Generated by `python3 tools/source_verification_usa.py` from the harvested "
            "snapshots (`data/manifest/snapshots.jsonl`), `reports/coverage_matrix_v0.csv` "
            "(`ggfiscal coverage`) and the built canonical layer (`ggfiscal build && ggfiscal "
            "reconcile`). Every number is measured; nothing is hand-filled (D13). Decisions: "
            "`DECISIONS.md` D-S16-001 onward; cell choices: `crosswalks/OECD_T12_to_ESA_EXP.csv` "
            "and `crosswalks/OECD_T12_T10_to_ESA_REV.csv`.",
            ""]

    # ---------------------------------------------------------------- harvest
    out += ["## 1. Harvest and reachability (D24)", ""]
    out += ["| source_id | part | retrieved | sha256 | bytes |", "|---|---|---|---|---|"]
    for r in _harvest_record():
        out.append(f"| {r['source_id']} | {r['part']} | {r['retrieved']} | `{r['sha256']}` | {r['bytes']} |")
    out += ["",
            "Blocked hosts, re-tested 2026-09-21 with browser headers: `www.cbo.gov` "
            "(HTTP 403, DataDome challenge; register `CBO_SITE`, status blocked) and "
            "`www.ssa.gov` (HTTP 403, Akamai; register `SSA_TRUSTEES`, status blocked). "
            "Both are registered with the D-S7-001 hand-retrieval route named as the unblock "
            "(OQ-13). Open: `sdmx.oecd.org`, `api.imf.org`, `ec.europa.eu` (AMECO), "
            "`apps.bea.gov` flat files, `www.federalreserve.gov`, `www.whitehouse.gov` "
            "(browser headers), `raw.githubusercontent.com` (CBO mirror), `www.cms.gov`. "
            "Fiscal Data (`api.fiscaldata.treasury.gov`, debt extension) needs literal "
            "brackets in `page[size]`; the URL builder keeps them (nothing pulled in U0).",
            ""]

    # ------------------------------------------------- first/last year per (line, source)
    out += ["## 2. First and last usable year per (line, source) — all 41 USA lines", "",
            "| classification | line | source_id | first | last | n | note |", "|---|---|---|---|---|---|---|"]
    order = {c: i for i, c in enumerate(config.TREES)}
    cov = cov.assign(_o=cov.classification.map(order)).sort_values(["_o", "line_code", "source_id"])
    for r in cov.itertuples():
        out.append(f"| {r.classification} | {r.line_code} | {r.source_id} | {int(r.first_usable_year)} | "
                   f"{int(r.last_usable_year)} | {int(r.n_years)} | {str(r.notes)[:140]} |")
    n_lines = cov.groupby(["classification", "line_code"]).ngroups
    out += ["", f"{n_lines} of 41 lines have measured coverage from at least one source "
                f"({(cov.status == 'measured').sum()} (line, source) rows); the three "
                "structural zeros (R01, E04, GF05) are covered by their `lines_absent` "
                "declaration (D20, source_id `structural_zero`).", ""]

    # ------------------------------------------------------- anchors and identities
    ote, otr, b9 = fam.totals(ISO3)["TE"], fam.totals(ISO3)["TR"], fam.totals(ISO3)["B9"]
    gdp, gdp_sid = fam.gdp(ISO3)
    out += ["## 3. Anchor tables (D18) and their identities", "",
            f"- OECD Table 12 flows, S13, USD mn, {int(ote.index.min())}-{int(ote.index.max())}: "
            f"OTE 2024 = {_mn(ote[2024])}; OTR 2024 = {_mn(otr[2024])}; B9 2024 = {_mn(b9[2024])}; "
            f"max |B9 − (OTR − OTE)| = {(b9 - (otr - ote)).abs().max():.3f} mn.",
            f"- ESA_EXP identity E01..E09 = OTE from the `oecd_t12` cells: max |diff| = "
            f"{_esa_identity(fam):.3f} mn over every year.",
            f"- Revenue identity R01..R10 = OTR from the family mapping: max |diff| = "
            f"{_rev_identity(fam, otr):.3f} mn over every year (R09 = P1O = P1M + P131, "
            f"max |P1O − (P1M + P131)| = {(t12('P1O', 'REV') - t12('P1M', 'REV') - t12('P131', 'REV')).abs().max():.3f}).",
            f"- COFOG: Table 11 `_T` vs Table 12 OTE differ by "
            f"{(fam.cofog_total(ISO3) - ote).min():,.0f} to {(fam.cofog_total(ISO3) - ote).max():,.0f} mn "
            "across 1970-2024 (two tables of the same institution; the COFOG tree's total is `_T`, "
            "the ledger's TE is OTE); Σ GF01..GF10 (ex GF05) = `_T` to "
            f"{(sum(fam.cofog(ISO3, f'GF{n:02d}') for n in range(1, 11) if n != 5) - fam.cofog_total(ISO3)).abs().max():.3f} mn.",
            f"- Table 10 detail: D51M + D51O = D51 (max |diff| {(RO.oecd_t10(ISO3, 'D51M') + RO.oecd_t10(ISO3, 'D51O') - RO.oecd_t10(ISO3, 'D51')).abs().max():.3f}); "
            f"T10 D5 − T12 D5 max |diff| {(RO.oecd_t10(ISO3, 'D5') - t12('D5', 'REV')).abs().max():,.1f} mn (lands in R05); "
            f"T10 D61 − T12 D61 max |diff| {(RO.oecd_t10(ISO3, 'D61') - t12('D61', 'REV')).abs().max():,.1f} mn (R06 takes T12).",
            f"- GDP: {gdp_sid} B1GQ current prices, {int(gdp.index.min())}-{int(gdp.index.max())}; 2024 = {_mn(gdp[2024])} mn "
            f"(= OECD EO GDP {_mn(RO.oecd_eo(ISO3, 'GDP')[2024])}).",
            f"- Interest concept: T11 D4 × GF01 − T12 D41 max |diff| = "
            f"{(RO.oecd_t11_item(ISO3, 'GF01', 'D4') - fam.d41_payable(ISO3)).abs().max():.1f} mn "
            f"(D26: the interest line is D.41); OECD EO GGINTP 2024 = {_mn(RO.oecd_eo(ISO3, 'GGINTP')[2024])} "
            f"vs T12 D41 {_mn(fam.d41_payable(ISO3)[2024])} (NIPA/IMA concept incl. imputed pension interest, "
            f"+{100 * (RO.oecd_eo(ISO3, 'GGINTP')[2024] / fam.d41_payable(ISO3)[2024] - 1):.2f}%).",
            ""]

    # ---------------------------------------------------------- structural zeros
    out += ["## 4. The three structural zeros in the anchor (D20)", "",
            "| line | anchor cell | years | max |value| | finding |", "|---|---|---|---|---|"]
    d211, d632 = t12("D211", "REV"), t12("D632", "EXP")
    gf05 = fam.cofog(ISO3, "GF05")
    out.append(f"| R01 | OECD_T12_REV D211 | {int(d211.index.min())}-{int(d211.index.max())} ({len(d211)}) | {d211.abs().max():.1f} | identically zero: no value-added tax |")
    out.append(f"| E04 | OECD_T12_EXP D632 | {int(d632.index.min())}-{int(d632.index.max())} ({len(d632)}) | {d632.abs().max():.1f} | identically zero: Medicare/Medicaid are D.62 (D6M = D62) |")
    out.append(f"| GF05 | OECD_T11 GF05 × OTE | no rows ({len(gf05)}) | — | Table 11 publishes no environmental-protection function for the USA; Σ of the nine published functions = `_T`, so GF05 is zero by additivity; the D4-by-function row for GF05 is 0 |")
    out += ["", "All three are published as `structural_zero` rows (grade A, 1970-2024) in the "
                "canonical layer; V41 OK.", ""]

    # ----------------------------------------------------------- D26 proxies
    out += ["## 5. D26 Level II proxies (NIPA Table 3.16, total-government block)", "",
            "| line | NIPA cell | years | 2024 (USD mn) | share of parent 2024 | share 2000 | share 1990 | concept |",
            "|---|---|---|---|---|---|---|---|"]
    d41 = fam.d41_payable(ISO3)
    for l2, parent in (("GF01_7", "GF01"), ("GF10_2", "GF10"), ("GF10_5", "GF10"), ("GF04_5", "GF04")):
        meta = config.tree_lines("COFOG")[l2]
        s, note = RB.level2_proxy(l2, meta["bea_nipa"])
        p = fam.cofog(ISO3, parent)
        cell = f"T31600:{meta['bea_nipa']['lines'][0]} {RB.nipa_label('T31600', meta['bea_nipa']['lines'][0])}"
        out.append(f"| {l2} | {cell} | {int(s.index.min())}-{int(s.index.max())} | {_mn(s[2024])} | "
                   f"{s[2024] / p[2024]:.4f} | {s[2000] / p[2000]:.4f} | {s[1990] / p[1990]:.4f} | {meta['bea_nipa']['note']} |")
    interest, _ = RB.level2_proxy("GF01_7", config.tree_lines("COFOG")["GF01_7"]["bea_nipa"])
    ratio = (interest / d41).dropna()
    out += ["",
            f"- GF01_7 is built from the D10 fallback (T12 D41 = T11 D4 × GF01; `level2_proxy_actual`, B), "
            f"as D26 says; the NIPA interest-payments cell is the cross-check: NIPA / T12 D41 runs from "
            f"{ratio.min():.4f} ({int(ratio.idxmin())}) to {ratio.max():.4f} ({int(ratio.idxmax())}), 2024 = {ratio[2024]:.4f} "
            "(NIPA/IMA interest incl. imputed pension interest).",
            "- GF10_2, GF10_5 and GF04_5 are built as `level2_proxy_actual` (B, concept_flag "
            "`level2_bea_function`) over the parent's anchor years 1970-2024; the remainders derive "
            "(V19 exact). The NIPA cells run from 1959 (U2 legs).",
            "- GF04_5: Table 3.17 publishes gross investment by function at Level I only (nine functions), "
            "so the D26 'current plus gross investment' for 04.5 is not constructible cell-for-cell; the "
            "proxy is the current-expenditure cell (OPEN_QUESTIONS.md OQ-15). The IMF GFS `GF0170_T` "
            f"cross-check exists {int(R.gfs_series(ISO3, 'cofog', 'GF0170_T').index.min())}-"
            f"{int(R.gfs_series(ISO3, 'cofog', 'GF0170_T').index.max())} only (reported, not used; V44 in U1).",
            ""]

    # ---------------------------------------------------------- the §3 wedges
    tot = RB.nipa_series("T30100", 37)
    rec = RB.nipa_series("T30100", 34)
    nlb = RB.nipa_series("T30100", 43)
    inv = RB.nipa_series("T30100", 39)
    ent = RB.nipa_series("T30100", 19)
    p1o = t12("P1O", "REV")
    out += ["## 6. The §3 concept wedges against NIPA (secondary national source)", "",
            "| wedge | 2024 (USD mn) | 2010 | 2000 | note |", "|---|---|---|---|---|"]
    for label, a, b, note in (
            ("sales grossing, expenditure side: OECD OTE − NIPA total expenditures (T3.1:37)", ote, tot,
             "the OECD grosses sales (P1O) that NIPA nets against consumption expenditures"),
            ("sales grossing, revenue side: OECD OTR − NIPA total receipts (T3.1:34)", otr, rec,
             "same grossing on the revenue side"),
            ("P1O itself (T12 REV)", p1o, None, "market output + own final use + payments for other non-market output = P.11 + P.12 + P.131"),
            ("balance: OECD B9 − NIPA net lending (T3.1:43)", b9, nlb,
             "kickoff §3 expects NLB unaffected; the residual wedge is the OECD/NIPA vintage and consolidation difference, measured here"),
            ("enterprise investment: NIPA gross government investment (T3.1:39) − OECD P5", inv, t12("P5", "EXP"),
             "government enterprises' gross investment sits inside NIPA government investment, outside the OECD P.51G (E08 wedge)"),
            ("enterprise surplus: NIPA current surplus of government enterprises (T3.1:19)", ent, None,
             f"NIPA concept; the OECD B2N (net operating surplus, balancing-items flow) is {_mn(t12('B2N', 'BAL')[2024])} in 2024 — neither is inside OTR (R10 carries D.39 + D.7 + D.9 − D.91 only)")):
        vals = []
        for y in (2024, 2010, 2000):
            va = a.get(y)
            if b is None:
                vals.append(_mn(va) if va is not None and pd.notna(va) else "—")
            else:
                vb = b.get(y)
                vals.append(_mn(va - vb) if va is not None and vb is not None and pd.notna(va) and pd.notna(vb) else "—")
        out.append(f"| {label} | {vals[0]} | {vals[1]} | {vals[2]} | {note} |")
    out += ["", "Table 3.16 'current expenditures' (total government) 2024 = "
                f"{_mn(RB.nipa_series('T31600', 1)[2024])} mn vs OTE {_mn(ote[2024])}: CFC in, investment out (§14) — "
                "never mixed with the ESA total in a Level II share without Table 3.17.", ""]

    # ---------------------------------------------------------- the §8.2 bridge
    br = pd.read_csv(REPO / "data" / "canonical" / "weo_base_bridge.csv")
    latest = next(iter(weo_vintages()))
    out += [f"## 7. §8.2 base-year bridge, WEO vintages (perimeter rule: `weo_perimeter_gap_expected: true`)", "",
            "| vintage | base year | overlap | mean NLB gap % TE | sigma | perimeter | unexplained | TR gap 2024 (mn) | TE gap 2024 | NLB gap 2024 | GDP gap 2024 |",
            "|---|---|---|---|---|---|---|---|---|---|---|"]
    for vintage in weo_vintages():
        g = br[(br.iso3 == ISO3) & (br.weo_vintage == vintage)]
        if g.empty:
            out.append(f"| {vintage} | — | 0 | | | | | | | | |")
            continue
        base = g[g.is_base_year]
        b_year = int(base.year.iloc[0]) if len(base) else None
        row24 = g[g.year == 2024]
        f = lambda c: _mn(row24[c].iloc[0]) if len(row24) and pd.notna(row24[c].iloc[0]) else "—"  # noqa: E731
        out.append(f"| {vintage} | {b_year} | {len(g)} | {g.gap_nlb_pct_te.mean():.3f} | {g.gap_nlb_pct_te.std():.3f} | "
                   f"{(g.classification == 'perimeter').sum()} | {(g.classification == 'unexplained').sum()} | "
                   f"{f('gap_tr_mn')} | {f('gap_te_mn')} | {f('gap_nlb_mn')} | {f('gap_gdp_mn')} |")
    g = br[(br.iso3 == ISO3) & (br.weo_vintage == latest)].sort_values("year")
    out += ["", f"Latest vintage {latest}: WEO US fiscal series start {int(g.year.min())} (kickoff §8.2), base year "
                f"{int(g[g.is_base_year].year.iloc[0])} (WEO latest actual 2025, anchor last year 2024). The NLB gap "
                f"ratio's sigma ({g.gap_nlb_pct_te.std():.2f}% of TE) exceeds the `perimeter_sigma_pct_te` tolerance "
                "(0.5) — V24 WARN on every vintage: the WEO's GFSM-basis US series carry documented adjustments "
                "(e.g. the 2017 repatriation tax removed from revenue) that are not a constant perimeter gap. "
                "Reported, not absorbed (D13, D16); the year-by-year rows are in `data/canonical/weo_base_bridge.csv`.",
            "", "| year | TR gap % TE | TE gap % TE | NLB gap % TE | classification |", "|---|---|---|---|---|"]
    for r in g.itertuples():
        out.append(f"| {int(r.year)} | {r.gap_tr_pct_te:.3f} | {r.gap_te_pct_te:.3f} | {r.gap_nlb_pct_te:.3f} | {r.classification} |")
    out.append("")

    # --------------------------------------------------- reconciliation sources
    out += ["## 8. Reconciliation and extension sources measured (for U2/U5)", "",
            f"- IMF GFS COFOG (USA): GF01_T {int(R.gfs_series(ISO3, 'cofog', 'GF01_T').index.min())}-"
            f"{int(R.gfs_series(ISO3, 'cofog', 'GF01_T').index.max())}; GFS SOO G21_T "
            f"{int(R.gfs_series(ISO3, 'soo', 'G21_T').index.min())}-{int(R.gfs_series(ISO3, 'soo', 'G21_T').index.max())}. "
            "V1 WARN rows on the USA (`exceptions.csv`) measure the GFSM-vs-SNA wedges per line and year.",
            f"- OECD Revenue Statistics (USA): T_1100 {int(R.oecd_rs_heading(ISO3, 'T_1100').index.min())}-"
            f"{int(R.oecd_rs_heading(ISO3, 'T_1100').index.max())}; `reports/recon_anchor_vs_oecd_rs_v0.csv` carries the "
            "heading-vs-line wedges (V25 WARN rows per line/year).",
            f"- AMECO (USA, Spring 2026): UYIG {int(R.ameco_series(ISO3, 'UYIG', 16).index.min())}-"
            f"{int(R.ameco_series(ISO3, 'UYIG', 16).index.max())}, URTG/UUTG from "
            f"{int(R.ameco_series(ISO3, 'UUTG', 16).index.min())}; the V5 overlap-growth diagnostics show the AMECO "
            "E-lines reproduce the T12 growth exactly (bias 0, rmse 0) except E09 (UKOG ≠ D.9).",
            f"- OECD EO (USA): every measure 1960-2027; 2024 YPGT {_mn(RO.oecd_eo(ISO3, 'YPGT')[2024])} vs OTE "
            f"{_mn(ote[2024])}; SSPG = D62 ({_mn(RO.oecd_eo(ISO3, 'SSPG')[2024])} vs {_mn(t12('D62', 'EXP')[2024])}); "
            f"SSRG = D61; TIND = D2; TYH {_mn(RO.oecd_eo(ISO3, 'TYH')[2024])} vs T10 D51M {_mn(RO.oecd_t10(ISO3, 'D51M')[2024])}; "
            f"TYB {_mn(RO.oecd_eo(ISO3, 'TYB')[2024])} vs D51O {_mn(RO.oecd_t10(ISO3, 'D51O')[2024])} (rest-of-world taxes).",
            f"- BEA NIPA flat files: register {len(RB.register()):,} (series, cell) rows; annual data "
            f"{RB.annual().year.min()}-{RB.annual().year.max()}; NIPA Table 3.1 total receipts/expenditures from "
            f"{int(tot.index.min())} — the §7.16 backward legs (U2).",
            ""]

    # ---------------------------------------------------------------- gate record
    ex = pd.read_csv(REPO / "data" / "canonical" / "exceptions.csv", dtype=str, keep_default_na=False)
    counts = ex.severity.value_counts().to_dict()
    out += ["## 9. Gate U0 evidence", "",
            f"- `ggfiscal coverage`: 164/164 lines covered (41 USA lines: {n_lines} measured or declared).",
            f"- `ggfiscal reconcile`: §8.2 bridge has a USA base-year row on every vintage (latest {latest}: base 2024).",
            f"- `ggfiscal validate`: ERROR={counts.get('ERROR', 0)}, WARN={counts.get('WARN', 0)}, OK={counts.get('OK', 0)} "
            "(S0_COVERAGE OK, S0_BRIDGE OK, V41 OK with 3 declared structural zeros).",
            "- USA-scoped findings: V1 WARN (IMF GFS wedges), V25 WARN (OECD RS wedges), V24 WARN (perimeter sigma), "
            "V5 OK/WARN (extension-source overlap diagnostics) — all intended visibility, none an ERROR.",
            "- GBR/FRA/DEU byte-identical (run_id excepted): `python3 tools/byte_identity.py /tmp/gg_baseline "
            "--countries GBR,FRA,DEU --new-file strict_USA.csv --new-crosswalk OECD_T12_to_ESA_EXP "
            "--new-crosswalk OECD_T12_T10_to_ESA_REV --new-scope register/CBO_SITE --new-scope register/SSA_TRUSTEES "
            "--check-now-scoped V24`.",
            ""]
    dest = REPO / "reports" / "source_verification_USA.md"
    dest.write_text("\n".join(out), encoding="utf-8")
    return dest


def _esa_identity(fam) -> float:
    total = None
    for code, meta in config.tree_lines("ESA_EXP").items():
        if config.is_total(meta):
            continue
        plus, minus = fam.esa_exp_parts(ISO3, meta)
        s = sum(plus[1:], plus[0]) - sum(minus, pd.Series(0.0, index=plus[0].index))
        total = s if total is None else total + s
    return float((total - fam.totals(ISO3)["TE"]).abs().max())


def _rev_identity(fam, otr) -> float:
    total = sum((s for s, _, _ in fam.revenue_lines(ISO3).values()), pd.Series(0.0, index=otr.index))
    return float((total - otr).abs().max())


if __name__ == "__main__":
    print(main())
